version: 0.0
os: linux
files:
  - source: /info.php
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: deploy/before_start.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/after_start.sh
      timeout: 300
      runas: root
